name: ERD Build
on:
  push:
    branches: [ "main" ]

jobs:
  build-erd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      - name: Generate schema.json
        run: tbls out -t json -o schema.json

      - name: Generate ER Diagrams
        run: npx @liam-hq/cli erd build --input schema.json --format tbls

    # - Next step: Deploy ERD `./dist` to your preferred hosting service for easy sharing and access.
